### ISSUE TITLE
Using CKAN with R (ckanr)

### ISSUE THREAD

**Issue by ratnanil** [opendata-swiss/ogd-handbook-wiki#39]
I have no clue where I should place this, so I'm just going to put it here in the hopes that someone will read this.

I've just tried out ckanr to access the ckan API with R, and it works great! I can do queries and get nice results, but one function does not seem to work. 

``` r
library(ckanr)
ckanr_setup(url = "https://opendata.swiss")

out <- package_search("abfall",as = "table",rows = 10)

out$results$name
#>  [1] "bauabfalle"                       
#>  [2] "auf-deponien-abgelagerte-abfalle" 
#>  [3] "siedlungsabfalle"                 
#>  [4] "sonderabfalle"                    
#>  [5] "siedlungsabfalle1"                
#>  [6] "abfallverbrennung"                
#>  [7] "abfallgefasse"                    
#>  [8] "entsorgungskalender-bioabfall"    
#>  [9] "sonderabfalle-nach-abfallgruppen1"
#> [10] "behandlung-von-sonderabfallen"

```

So far so good. But If I want to show a specific package, the function [`package_show()`](https://github.com/ropensci/ckanr#packages) returns a 404 error (when I try to `show `[this package](https://opendata.swiss/de/dataset/amtliches-ortschaftenverzeichnis-mit-postleitzahl-und-perimeter) for example.) 

``` r
package_show("972cd117-f1ed-4818-be14-233d89ab9fdf@bundesamt-fur-landestopografie-swisstopo")
#> Error: 404 - Not Found Error
#>   message Nicht gefunden
```

Removing the string after the `@` brings no luck either..
``` r
package_show("972cd117-f1ed-4818-be14-233d89ab9fdf")
#> Error: 404 - Not Found Error
#>   message Nicht gefunden
```
Any ideas as to what could be going wrong?

**Comment by metaodi** [comment]
package_show accepts either the `name` or the `id` of a dataset.

Your example `972cd117-f1ed-4818-be14-233d89ab9fdf@bundesamt-fur-landestopografie-swisstopo` is the `identifier`, so this does not work unfortunately.

Do get from the identifier to the correct name, you can use the ogdch_dataset_by_identifier API:

https://opendata.swiss/api/3/action/ogdch_dataset_by_identifier?identifier=972cd117-f1ed-4818-be14-233d89ab9fdf@bundesamt-fur-landestopografie-swisstopo

So if you call `package_show` with either `amtliches-ortschaftenverzeichnis-mit-postleitzahl-und-perimeter` or `dc188622-3b53-4810-884a-1f9233576b2c` you should get the correct result.

Both `name` and `id` are fields automatically assigned by CKAN, the `identifier` on the other hand is given by the publisher. This ensures that you always get the correct dataset with that identifier, no matter where you get it from.

**Comment by ratnanil** [comment]
Oh, my mistake! I was certain that hash code was the id.. works like a charm now!

Great work by the way, cool stuff!

**Comment by usernamefghh** [comment]
on

**Comment by usernamefghh** [comment]
on

**Comment by usernamefghh** [comment]
issue

**Comment by loleg** [comment]
@ratnanil thanks for the post - perhaps you'd like to share your experiences on a community hangout like https://forum.schoolofdata.ch + social media?

**Comment by ratnanil** [comment]
@loleg Thanks for the link. I've registered myself to the forum and will post something when I find the time!

**Comment by loleg** [comment]
@ratnanil meanwhile, your issue motivated me to rewrite this tutorial: https://github.com/dataletsch/ogd-handbook-wiki/wiki/Accessing-CKAN-in-R
